<?xml version="1.0"?>
<package format="2">
  <name>thorp_bringup</name>
  <version>0.1.0</version>
  <description>Basic configuration and launch files for Thorp robot</description>
  <maintainer email="jsantossimon@gmail.com">Jorge Santos Simón</maintainer>
  <author email="jsantossimon@gmail.com">Jorge Santos Simón</author>

  <license>BSD</license>

  <url type="bugtracker">https://github.com/corot/thorp/issues</url>
  <url type="repository">https://github.com/corot/thorp</url>
  <url type="website">http://wiki.ros.org/thorp_bringup</url>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>python3-tk</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>actionlib</exec_depend>
  <exec_depend>openni2_launch</exec_depend>
  <exec_depend>freenect_launch</exec_depend>
  <exec_depend>depthimage_to_laserscan</exec_depend>
  <exec_depend>pointcloud_to_laserscan</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>kobuki_auto_docking</exec_depend>
  <exec_depend>kobuki_safety_controller</exec_depend>
  <exec_depend>turtlebot_bringup</exec_depend>
  <exec_depend>turtlebot_dashboard</exec_depend>
  <exec_depend>yocs_cmd_vel_mux</exec_depend>
  <exec_depend>yocs_velocity_smoother</exec_depend>
  <exec_depend>rviz_textured_quads</exec_depend>
  <exec_depend>jsk_rviz_plugins</exec_depend>
  <exec_depend>ipa_building_navigation</exec_depend>
  <exec_depend>ipa_room_segmentation</exec_depend>
  <exec_depend>ipa_room_exploration</exec_depend>

  <exec_depend>thorp_msgs</exec_depend>
  <exec_depend>thorp_boards</exec_depend>
  <exec_depend>thorp_toolkit</exec_depend>
  <exec_depend>thorp_description</exec_depend>
  <exec_depend>thorp_moveit_config</exec_depend>
  <exec_depend>thorp_navigation</exec_depend>
  <exec_depend>thorp_perception</exec_depend>
  <exec_depend>thorp_manipulation</exec_depend>
  <exec_depend>thorp_rviz_plugins</exec_depend>
</package>
