<?xml version="1.0"?>
<package format="2">
  <name>thorp_smach</name>
  <version>0.1.0</version>
  <description>SMACH state machines for Thorp robot</description>
  <maintainer email="jsantossimon@gmail.com">Jorge Santos Simón</maintainer>
  <author email="jsantossimon@gmail.com">Jorge Santos Simón</author> 

  <license>BSD</license>

  <url type="bugtracker">https://github.com/corot/thorp/issues</url>
  <url type="repository">https://github.com/corot/thorp</url>

  <buildtool_depend>catkin</buildtool_depend>
  
  <exec_depend>tf</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>smach</exec_depend>
  <exec_depend>smach_ros</exec_depend>
  <exec_depend>smach_viewer</exec_depend>
  <exec_depend>actionlib</exec_depend>
  <exec_depend>actionlib_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>moveit_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>shape_msgs</exec_depend>
  <exec_depend>control_msgs</exec_depend>
  <exec_depend>arbotix_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>
  <exec_depend>ipa_building_msgs</exec_depend>
  <exec_depend>cob_perception_msgs</exec_depend>

  <exec_depend>thorp_msgs</exec_depend>
  <exec_depend>thorp_toolkit</exec_depend>
</package>
