# Cannon command service:
#  - action can be tilt, fore or both
#  - angle is expected in degrees, 0 for horizontal
#  - the cannon can fire continuously up to 6 shots

uint8 TILT = 1
uint8 FIRE = 2
uint8 BOTH = 3

uint8 action
float32 angle
uint8 shots

---
# result definition
ThorpError error
