# Cannon command service:
#  - action can be aim, tilt or fire
#  - aim requires an externally provided target
#  - angle is expected in degrees, 0 for horizontal
#  - the cannon can fire continuously up to 6 shots

uint8 AIM  = 1
uint8 TILT = 2
uint8 FIRE = 3

uint8 action
float32 angle  # required only for TILT
uint8 shots    # required only for FIRE

---
# result definition
ThorpError error
