# name of the object detection model
model_name: "ssd_mobilenet_v1_coco_2017_11_17"

# number of classes in dataset
num_of_classes: 90

# name of the label pbtxt file
label_file: "mscoco_label_map.pbtxt"

# Set your RGB image topic here, default is for openni2
#camera_namespace: "/kinect/rgb/image_rect_color"
camera_namespace: "/kinect/rgb/image_raw"

# Set your depth image topic here, default is for openni2
#depth_namespace: "/kinect/depth_registered/hw_registered/image_rect"
depth_namespace: "/kinect/depth_registered/image_raw"

# Video name, if you provide a video name with path algorithm will run on it, otherwise write "no" for getting from camera
video_name: "no"

#number of threads for tensorflow, this paramareter will define the values of
# intra_op_parallelism_threads=num_workers,
# inter_op_parallelism_threads=num workers ,
# if it is -1, then the decision will be made by tensorflow
num_workers: -1
