DEFAULT_PLANNER = 'GlobalPlanner'
DEFAULT_CONTROLLER = 'TEBPlanner'
FOLLOW_CONTROLLER = 'PoseFollower'
FOLLOW_RECOVERY = ['clear_local_cm', 'escape_distance']
GET_PATH_RECOVERY = ['clear_global_cm']
EXE_PATH_RECOVERY = ['clear_local_cm', 'escape_distance', 'out_to_free_space']
MOVE_BASE_RECOVERY = ['clear_both_cms', 'escape_distance', 'out_to_free_space']
TIGHT_DIST_TOLERANCE = 0.035
TIGHT_ANGLE_TOLERANCE = 0.05  # ~3 deg
LOOSE_DIST_TOLERANCE = 0.25
LOOSE_ANGLE_TOLERANCE = 0.5  # ~30 deg
INF_ANGLE_TOLERANCE = float('inf')
WP_REACHED_THRESHOLD = 1.0  # we consider a waypoint reached when we pass by at least this distance
TABLE_MIN_SIDE = 0.4  # TODO enough to reject shelves, that I cannot handle by now (doll table side is 45 cm)
TABLE_MAX_SIDE = 1.0  # TODO I cannot handle such a large table, as I only go to the center of the four sides
APPROACH_DIST_TO_TABLE = 0.3  # close enough to properly detect tabletop objects but not for picking
DETACH_DIST_FROM_TABLE = 0.4  # far enough to safely navigate around the table to other picking poses
CLEAR_TABLE_WAY_TIMEOUT = 15.0  # seconds; restore costmap after this time
PICKING_MAX_FAILURES = 3  # picking failures allowed for each object on current picking location (resets upon moving)
PICKING_DIST_TO_TABLE = 0.15  # ideal picking distance to the table, as close as possible without risk
PLACING_HEIGHT_ON_TABLE = 0.005  # slightly above the table to avoid crashing the object against it
PLACING_HEIGHT_ON_TRAY = 0.03  # well above the tray to avoid colliding with (or ejecting) previously placed objects
GRIPPER_MAX_EFFORT = 0.03  # max effort exerted by the gripper on grasping (stops closing upon reaching this value)
GRIPPER_TIGHTENING = 0.002  # additional gripper closing to tighten grasped objects
MAX_ARM_REACH = 0.3
TRAY_SIDE_X = 0.14
TRAY_SIDE_Y = 0.14
TRAY_DEPTH = 0.02
TRAY_SLOT = 0.035  # better a divisor of both tray sides
