debug: true
point_cloud_topic: /xtion/depth_registered/points
zones_config: $(find thorp_perception)/config/rail/zones.yaml
min_cluster_size: 200
max_cluster_size: 10000
cluster_tolerance: 0.01
use_color: true
crop_first: true
label_markers: true
