- name: "Default Zone"
  remove_surface: true
  require_surface: true
  parent_frame_id: "map"
  child_frame_id: "xtion_depth_frame"
  bounding_frame_id: "base_footprint"
  segmentation_frame_id: "base_footprint"
  x_min: +0.2
  x_max: +2.5
  y_min: -1.0
  y_max: +1.0
  z_max: +0.5
  z_min: +0.3
