# Simulated arm has no backlash, so we undo (mostly) pick and place tweaks
manipulation:
  ros__parameters:
    arm_ref_frame: arm_base_link
    vertical_backlash_scale: 0.0
    vertical_backlash_delta: 0.0
    fall_short_distance_delta: 0.0
    gripper_asymmetry_yaw_delta: 0.01
    # One-sided gripper model, converting openings into gripper joint angles
    gripper:
      center: 0.07
      pad_width: 0.025
      finger_length: 0.03
