manipulation:
  ros__parameters:
    arm_ref_frame: arm_base_link
    vertical_backlash_scale: 1.0         # Fully compensate for low pitch poses
    vertical_backlash_delta: 0.0125      # Increment z to cope with backlash
    fall_short_distance_delta: 0.015     # Increment distance... no justification, really; it
                                         # just put the target in the center of the gripper!
    gripper_asymmetry_yaw_delta: 0.12    # Increment the yaw to compensate that only the right finger
                                         # opens, and so there's more grasping room on the right
    # One-sided gripper model, converting openings into gripper joint angles
    gripper:
      center: 0.07
      pad_width: 0.025
      finger_length: 0.03
