planning_plugins:
  - ompl_interface/OMPLPlanner
request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization
  - default_planning_response_adapters/ValidateSolution
  - default_planning_response_adapters/DisplayMotionPath
arm:
  default_planner_config: RRTConnect
  planner_configs: [RRTConnect, RRT, RRTstar, PRM, PRMstar, KPIECE, BKPIECE, LBKPIECE, EST, SBL, BiTRRT, TRRT]
gripper:
  default_planner_config: RRTConnect
  planner_configs: [RRTConnect, RRT]
