<?xml version="1.0"?>
<package format="2">
  <name>thorp_perception</name>
  <version>0.1.0</version>
  <description>
   Thorp perception includes:
    - pipelines (RAIL, COB, ORK) configuration and launchers
    - high-level object recognition action server
    - target objects generation scripts
  </description>
  <maintainer email="jsantossimon@gmail.com">Jorge Santos Simón</maintainer>
  <author email="jsantossimon@gmail.com">Jorge Santos Simón</author>

  <license>BSD</license>

  <url type="bugtracker">https://github.com/corot/thorp/issues</url>
  <url type="repository">https://github.com/corot/thorp</url>
  <url type="website">http://wiki.ros.org/thorp_perception</url>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>tf</depend>
  <depend>roscpp</depend>
  <depend>pcl_ros</depend>
  <depend>actionlib</depend>
  <depend>shape_msgs</depend>
  <depend>object_recognition_msgs</depend>
  <depend>rail_manipulation_msgs</depend>
  <depend>rail_mesh_icp</depend>
  <depend>geometry_msgs</depend>
  <depend>moveit_msgs</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>cv_bridge</depend>
  <depend>image_geometry</depend>
  <depend>image_transport</depend>
  <depend>nlohmann-json-dev</depend>
  <depend>libomp-dev</depend>

  <depend>thorp_msgs</depend>
  <depend>thorp_toolkit</depend>

  <exec_depend>rail_segmentation</exec_depend>
  <exec_depend>cob_people_object_detection_tensorflow</exec_depend>

  <!-- optional meshes handling tools:
  <exec_depend>admesh</run_depend>
  <exec_depend>meshlab</run_depend>
  <exec_depend>couchdb</run_depend>
  <exec_depend>openscad</run_depend>
   -->
</package>
