# goal definition

string output_frame    # detected objects reference frame (ignored by RAIL)
bool clear_scene       # clear previous planning scene objects

---

# result definition

moveit_msgs/CollisionObject surface
moveit_msgs/CollisionObject[] objects

---

# feedback
