# goal definition

string[] object_names
string   output_frame

---

# result definition

string object_name
geometry_msgs/PoseStamped pickup_pose
geometry_msgs/PoseStamped place_pose

---

# feedback
