# Follow pose: try to follow poses received on 'target_pose' topic at target_distance.
# Goal succeeds upon reaching target_distance if stop_at_distance is true, or after
# exec_time_limit seconds pass, if it's not set to 0.
# Aborted if no poses are received for 'no_pose_timeout' seconds.
# Otherwise, runs until preempted.

# goal definition

float32 target_distance     # following desired distance; use the configured value if <= 0
bool stop_at_distance       # stop action upon reaching the desired following distance
duration exec_time_limit    # stop action after this time, whatever happens; ignored if 0
duration no_pose_timeout    # stop action after this time without receiving poses

---

# result definition

uint8 WITHIN_DISTANCE = 0
uint8 RUN_OUT_OF_TIME = 1
uint8 NO_POSE_TIMEOUT = 2
uint8 FOLLOW_CANCELED = 3

uint8 outcome

---

# feedback

float32 dist_to_target
float32 angle_to_target
geometry_msgs/Twist cmd                # last command calculated by the controller
geometry_msgs/PoseStamped target_pose  # last target pose received, in robot reference frame
