uint8 JOINT_STATE  = 1
uint8 POSE_TARGET  = 2
uint8 NAMED_TARGET = 3

# goal definition
uint8 target_type

string named_target
sensor_msgs/JointState joint_state
geometry_msgs/PoseStamped pose_target

---

# result definition

ThorpError error

---

# feedback
