# goal definition

string object_name
string support_surf
geometry_msgs/PoseStamped place_pose

---

# result definition

ThorpError error

---

# feedback
string stage  # "planning", or the task stage being executed, e.g. "approach object"
